package common

type AirlineIdentifier string

const (
	Lufthansa         AirlineIdentifier = "LH"
	AirDolomiti       AirlineIdentifier = "EN"
	Swiss             AirlineIdentifier = "LX"
	Austrian          AirlineIdentifier = "OS"
	Edelweiss         AirlineIdentifier = "WK"
	Brussels          AirlineIdentifier = "SN"
	EurowingsDiscover AirlineIdentifier = "4Y"
	Aegean            AirlineIdentifier = "A3"
	LHCity            AirlineIdentifier = "VL"
	AirBaltic         AirlineIdentifier = "BT"
	LATAM             AirlineIdentifier = "LA"
	SunExpress        AirlineIdentifier = "XQ"
	ANA               AirlineIdentifier = "NH"
	AirIndia          AirlineIdentifier = "AI"
	Eurowings         AirlineIdentifier = "EW"
	LOT               AirlineIdentifier = "LO"
	Croatia           AirlineIdentifier = "OU"
	KMMaltaAirlines   AirlineIdentifier = "KM"
	Airlink           AirlineIdentifier = "4Z"
	AirCanada         AirlineIdentifier = "AC"
	Luxair            AirlineIdentifier = "LG"
	TAP               AirlineIdentifier = "TP"
	CathayPacific     AirlineIdentifier = "CX"
	AirChina          AirlineIdentifier = "CA"
	AirNewZealand     AirlineIdentifier = "NZ"
	EgyptAir          AirlineIdentifier = "MS"
	SingaporeAirlines AirlineIdentifier = "SQ"
	Vistara           AirlineIdentifier = "UK"
	United            AirlineIdentifier = "UA"
	SouthAfrican      AirlineIdentifier = "SA"
	OmanAir           AirlineIdentifier = "WY"
	AirAstana         AirlineIdentifier = "KC"
	Avianca           AirlineIdentifier = "AV"
	Etihad            AirlineIdentifier = "EY"
	Ethiopian         AirlineIdentifier = "ET"
	THAI              AirlineIdentifier = "TH"
	AirFrance         AirlineIdentifier = "AF"
	THAITG            AirlineIdentifier = "TG"
	AsianaOZ          AirlineIdentifier = "OZ"
	BangkokAirways    AirlineIdentifier = "PG"
	AccessRail        AirlineIdentifier = "9B"
	Scandinavian      AirlineIdentifier = "SK"
	Georgian          AirlineIdentifier = "A9"
)
